version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - quatty:/var/lib/mysql

volumes:
  quatty: